version: "3.7"

services:
  dive-into-kotlin:
    container_name: dive-into-kotlin-stage
    image: "ijohnnymiller/dive-into-kotlin-stage:${TAG}"
    ports:
      - "8080:8080"
    networks:
      dive_into_kotlin_network:
        ipv4_address: 172.16.239.10

networks:
  dive_into_kotlin_network:
    ipam:
      driver: default
      config:
        - subnet: "172.11.239.0/24"
